services:
  paper:
    build: .
    container_name: murder_paper
    ports:
      - "25565:25565"
    volumes:
#      - ./spigot:/var/spigot
      - ./paper:/var/paper
    stdin_open: true
    tty: true
